version: "3"

services:
  influxdb:
    image: influxdb:1.4.3
    volumes:
      - influxdb-data:/var/lib/influxdb
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana:5.0.4
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
 influxdb-data:
 grafana-data: